pass_argument.exe: pass_argument.o
	g++.exe pass_argument.o -LC:\SDK\boost_1_69_0\bin\gcc_all_static\lib -lboost_thread-mgw82-mt-s-x32-1_69 -o pass_argument.exe

pass_argument.o: pass_argument.cc
	g++.exe -c -IC:\SDK\boost_1_69_0 -Wall -std=c++0x pass_argument.cc